spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authrestricted
    username: root
    password: Mustarel2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351